name: Test CI
on: [push]
jobs:
  info-job:
    runs-on: ubuntu-latest
    steps:
      - name: Repo information
        run: |
         echo "Event: ${{ github.event_name }}"
         echo "Repository: ${{ github.repository }}"
         echo "Brunch: ${{ github.brunch }}"
         echo "Workspace: ${{ github.workspace }}"
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: ls -la
