name: Test CI
on:
#  push:
#    branches: [test-ci]
  workflow_dispatch:
    inputs:
      version:
        description: "Image version"
        required: true
        default: "0.1.0"
jobs:
  info_job:
    runs-on: ubuntu-latest
    steps:
      - name: Repo information
        run: |
         echo "Event: ${{ github.event_name }}"
         echo "Repository: ${{ github.repository }}"
         echo "Branch: ${{ github.branch }}"
         echo "Workspace: ${{ github.workspace }}"
  check_tools:
    runs-on: ubuntu-latest
    steps:
      - name: Check installed tools
        run: |
         aws --version
         docker --version
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t test-image:${{ github.event.inputs.version }} -f Dockerfile .
      - run: docker images
